<a href="https://colab.research.google.com/github/abou-zithar/Chat-Bot-using-RNN-NLP/blob/main/chatBot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import json
import re
import numpy as np 
import tensorflow as tf
from tensorflow.keras.utils import to_categorical


In [ ]:
with open('data.json') as file:
  data=json.load(file)

In [ ]:
data

{'data': [{'label': 'greeting',
   'patterns': ['Hi', 'Hey', 'Is anyone there?', 'Hello', 'Hay'],
   'responses': ['Hello', 'Hi', 'Hi there', 'Hey']},
  {'label': 'about',
   'patterns': ['Who are you?', 'What are you?', 'Who you are?'],
   'responses': ["I'm Zain, your bot assistant",
    "I'm Zain , an Artificial Intelligent bot",
    "I'm Zain , an Amit Artificial Intelligent bot"]},
  {'label': 'name',
   'patterns': ['what is your name?',
    'what should I call you?',
    'whats your name?'],
   'responses': ['You can call me Zain.',
    "I'm Zain!",
    'Just call me as Zain']},
  {'label': 'help',
   'patterns': ['Could you help me?',
    'give me a hand please.',
    'Can you help?',
    'What can you do for me?',
    'I need a support.',
    'I need a help',
    'support me please'],
   'responses': ['Tell me how can assist you',
    'Tell me your problem to assist you',
    'Yes Sure, How can I support you']},
  {'label': 'sad',
   'patterns': ["I'm sad",
    "I'm so sad",
 

In [ ]:
trainning_example=[]
trainning_label=[]

for example in data['data']:
  for pattern in example['patterns']:
    trainning_example.append(pattern)
    trainning_label.append(example['label'])


#preprocessing

In [ ]:
def cleanText(pattern):
  result=[]
  for sent in pattern:
    sent=re.sub('\W'," ",sent)
    sent=sent.lower()
    result.append(sent)

  return result


In [ ]:
trainning=cleanText(trainning_example)
trainning

['hi',
 'hey',
 'is anyone there ',
 'hello',
 'hay',
 'who are you ',
 'what are you ',
 'who you are ',
 'what is your name ',
 'what should i call you ',
 'whats your name ',
 'could you help me ',
 'give me a hand please ',
 'can you help ',
 'what can you do for me ',
 'i need a support ',
 'i need a help',
 'support me please',
 'i m sad',
 'i m so sad',
 'i feel bad',
 'i am alone',
 'i have a lot of problems',
 'i am depressed',
 'i need encouragement',
 'i m so frustrated',
 'i m so frustrated with myself because i lost confidence',
 'thanks',
 'thank you',
 'that s helpful',
 'thanks for the help',
 'bye',
 'see you later',
 'goodbye']

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
trainnig_labels=le.fit_transform(trainning_label)

In [ ]:
labels=to_categorical(trainnig_labels)

In [ ]:
labels

array([[0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 

In [ ]:
# Tokenizer which give every word unique value 

In [ ]:
from tensorflow.keras.preprocessing.text import Tokenizer

## convert tWord to vector

In [ ]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(trainning)
sequances=tokenizer.texts_to_sequences(trainning)
# every word get a value which represent the importance of this word 

In [ ]:
print(trainning)

['hi', 'hey', 'is anyone there ', 'hello', 'hay', 'who are you ', 'what are you ', 'who you are ', 'what is your name ', 'what should i call you ', 'whats your name ', 'could you help me ', 'give me a hand please ', 'can you help ', 'what can you do for me ', 'i need a support ', 'i need a help', 'support me please', 'i m sad', 'i m so sad', 'i feel bad', 'i am alone', 'i have a lot of problems', 'i am depressed', 'i need encouragement', 'i m so frustrated', 'i m so frustrated with myself because i lost confidence', 'thanks', 'thank you', 'that s helpful', 'thanks for the help', 'bye', 'see you later', 'goodbye']


In [ ]:
print(sequances)

[[23], [24], [11, 25, 26], [27], [28], [12, 8, 2], [3, 8, 2], [12, 2, 8], [3, 11, 13, 14], [3, 29, 1, 30, 2], [31, 13, 14], [32, 2, 4, 5], [33, 5, 6, 34, 15], [16, 2, 4], [3, 16, 2, 35, 17, 5], [1, 9, 6, 18], [1, 9, 6, 4], [18, 5, 15], [1, 7, 19], [1, 7, 10, 19], [1, 36, 37], [1, 20, 38], [1, 39, 6, 40, 41, 42], [1, 20, 43], [1, 9, 44], [1, 7, 10, 21], [1, 7, 10, 21, 45, 46, 47, 1, 48, 49], [22], [50, 2], [51, 52, 53], [22, 17, 54, 4], [55], [56, 2, 57], [58]]


In [ ]:
# want to make sure that the size of the input all the same so we will make padding


#padding


In [ ]:
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [ ]:
paded_sequences=pad_sequences(sequances,maxlen=15)

In [ ]:
print(paded_sequences)

[[ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 23]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 24]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 11 25 26]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 27]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  0  0 28]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 12  8  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  3  8  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 12  2  8]
 [ 0  0  0  0  0  0  0  0  0  0  0  3 11 13 14]
 [ 0  0  0  0  0  0  0  0  0  0  3 29  1 30  2]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 31 13 14]
 [ 0  0  0  0  0  0  0  0  0  0  0 32  2  4  5]
 [ 0  0  0  0  0  0  0  0  0  0 33  5  6 34 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 16  2  4]
 [ 0  0  0  0  0  0  0  0  0  3 16  2 35 17  5]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  9  6 18]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  9  6  4]
 [ 0  0  0  0  0  0  0  0  0  0  0  0 18  5 15]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1  7 19]
 [ 0  0  0  0  0  0  0  0  0  0  0  1  7 10 19]
 [ 0  0  0  0  0  0  0  0  0  0  0  0  1

# Models

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Embedding,GlobalAveragePooling1D

In [ ]:
model=Sequential()
model.add(Embedding(500,10,input_length=15))
model.add(GlobalAveragePooling1D())
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(8,activation='softmax'))

In [ ]:
model.compile(loss='categorical_crossentropy',optimizer='adam',metrics=['accuracy'])
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, 15, 10)            5000      
                                                                 
 global_average_pooling1d (G  (None, 10)               0         
 lobalAveragePooling1D)                                          
                                                                 
 dense (Dense)               (None, 10)                110       
                                                                 
 dense_1 (Dense)             (None, 10)                110       
                                                                 
 dense_2 (Dense)             (None, 8)                 88        
                                                                 
Total params: 5,308
Trainable params: 5,308
Non-trainable params: 0
____________________________________________________

In [ ]:
model.fit(paded_sequences,labels,epochs=450)

Epoch 1/450
2/2 [==============================] - 3s 10ms/step - loss: 2.0794 - accuracy: 0.1176
Epoch 2/450
2/2 [==============================] - 0s 6ms/step - loss: 2.0780 - accuracy: 0.2059
Epoch 3/450
2/2 [==============================] - 0s 7ms/step - loss: 2.0774 - accuracy: 0.2059
Epoch 4/450
2/2 [==============================] - 0s 7ms/step - loss: 2.0767 - accuracy: 0.2059
Epoch 5/450
2/2 [==============================] - 0s 7ms/step - loss: 2.0762 - accuracy: 0.2059
Epoch 6/450
2/2 [==============================] - 0s 10ms/step - loss: 2.0758 - accuracy: 0.2059
Epoch 7/450
2/2 [==============================] - 0s 7ms/step - loss: 2.0754 - accuracy: 0.2059
Epoch 8/450
2/2 [==============================] - 0s 7ms/step - loss: 2.0752 - accuracy: 0.2059
Epoch 9/450
2/2 [==============================] - 0s 6ms/step - loss: 2.0747 - accuracy: 0.2059
Epoch 10/450
2/2 [==============================] - 0s 6ms/step - loss: 2.0744 - accuracy: 0.2059
Epoch 11/450
2/2 [=========

#test

In [ ]:
inp='hello'
sent=pad_sequences(tokenizer.texts_to_sequences([inp]),maxlen=15)
sent

array([[ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 27]],
      dtype=int32)

In [ ]:
result=np.argmax(model.predict(sent))

In [ ]:
final_result=le.inverse_transform(np.array(result).reshape(1))

In [ ]:
final_result

array(['greeting'], dtype='<U12')

## interface

In [ ]:
def userChat():
  print('# note # to close the app write Quit ###')
  print('#_______________________________________')
  while True:

    print('user : ',end='')
    inp=input()

    inp=re.sub('\W'," ",inp).lower()

    if inp.lower() == 'quit':
      break

    sent=pad_sequences(tokenizer.texts_to_sequences([inp]),maxlen=15)
    result=np.argmax(model.predict(sent))
    final_result=le.inverse_transform(np.array(result).reshape(1))


    for label in data['data']:
      if label['label']==final_result:
        print('Chat Bot : ',np.random.choice(label['responses']))
  


In [ ]:
print('start conversation with chat bot')
userChat()

start conversation with chat bot
to close the app write Quit
user : quit
